var ArticleConstants = {
  ARTICLE_RECEIVED: "ARTICLE_RECEIVED",
  ARTICLES_RECEIVED: "ARTICLES_RECEIVED",
  HEADER_IMAGE_RECEIVED: "HEADER_IMAGE_RECEIVED",
  PINNED_ARTICLE_RECEIVED: "PINNED_ARTICLE_RECEIVED",
};

module.exports = ArticleConstants;
