# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb68a1f420e7c8d30382489236df3fb7079d1f3df6bc112f4c138b11b4d055fac82a8dae0a376867d21af5a3ac56bef2e470ac0caff83f4d411a78c638c77d06

test:
  secret_key_base: d8ad92e3057273aa3b4fd9b1b180697baac3daf8597072b5c4ab6faa3a19d6142ee11fe897d4c3ef21894e88bd5a7e01144f7d9eabe23dfc9ef110bf151f38ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
